// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFluentAPIDemo.Data;

#nullable disable

namespace WebFluentAPIDemo.Migrations
{
    [DbContext(typeof(WebFluentAPIDemoContext))]
    [Migration("20260330053934_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebFluentAPIDemo.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            CreatedAt = new DateTime(2026, 3, 30, 5, 39, 33, 382, DateTimeKind.Utc).AddTicks(6310),
                            FuelType = "Petrol",
                            IsAvailable = true,
                            Make = "Toyota",
                            Mileage = 15000,
                            Model = "Corolla",
                            Price = 20000m,
                            SeatingCapacity = 5,
                            Transmission = "Automatic",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            CreatedAt = new DateTime(2026, 3, 30, 5, 39, 33, 382, DateTimeKind.Utc).AddTicks(6314),
                            FuelType = "Petrol",
                            IsAvailable = true,
                            Make = "Honda",
                            Mileage = 20000,
                            Model = "Civic",
                            Price = 22000m,
                            SeatingCapacity = 5,
                            Transmission = "Manual",
                            Year = 2019
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
